#!/usr/bin/env python3
"""Regenerate the source table in README.md from data/mechanisms.json.

The assignment is graded on the dates, so the README's citation table is
generated from the same file the site renders. It cannot drift out of sync
with the page, because there is only one copy of the data.

    python tools/build_readme_sources.py
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "mechanisms.json"
README = ROOT / "README.md"

BEGIN = "<!-- SOURCES:BEGIN - generated by tools/build_readme_sources.py, do not edit by hand -->"
END = "<!-- SOURCES:END -->"


def esc(s):
    return str(s).replace("|", "\\|")


def main():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    mechs = sorted(data["mechanisms"], key=lambda m: (m["date"], m["name"]))

    rows = [
        "| # | Date | Mechanism | Source document | ID | Date type | Verified |",
        "|---|------|-----------|-----------------|----|-----------|----------|",
    ]
    for i, m in enumerate(mechs, 1):
        c = m.get("citation", {})
        ident = esc(c.get("id", ""))
        if c.get("url"):
            ident = f"[{ident}]({c['url']})"
        rows.append(
            "| {n} | `{date}` | **{name}** | {title} | {ident} | {kind} | {ok} |".format(
                n=i,
                date=m["date"],
                name=esc(m["name"]),
                title=esc(c.get("title", "")),
                ident=ident,
                kind=esc(m.get("dateKind", "")),
                ok="yes" if c.get("verified") else "**NO**",
            )
        )

    verified = sum(1 for m in mechs if m.get("citation", {}).get("verified"))
    kinds = {}
    for m in mechs:
        kinds[m.get("dateKind", "?")] = kinds.get(m.get("dateKind", "?"), 0) + 1
    summary = ", ".join(f"{v} x `{k}`" for k, v in sorted(kinds.items(), key=lambda kv: -kv[1]))

    block = "\n".join(
        [
            BEGIN,
            "",
            f"**{len(mechs)} mechanisms, {mechs[0]['date'][:4]}-{mechs[-1]['date'][:4]}. "
            f"{verified} of {len(mechs)} dates checked against the primary source.** "
            f"Date types: {summary}.",
            "",
            *rows,
            "",
            END,
        ]
    )

    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit("README.md is missing the SOURCES markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    README.write_text(head + block + tail, encoding="utf-8")
    print(f"README.md source table rebuilt: {len(mechs)} rows, {verified} verified")


if __name__ == "__main__":
    main()
